//Register
export const REGISTERING = "REGISTERING";
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

//Get Rooms
export const FETCHING_ROOMS = "FETCHING_ROOMS";
export const FETCHING_ROOMS_SUCCESS = "FETCHING_ROOMS_SUCCESS";
export const FETCHING_ROOMS_FAILURE = "FETCHING_ROOMS_FAILURE";

//Get Friends List
export const FETCHING_FRIENDS = "FETCHING_FRIENDS";
export const FETCHING_FRIENDS_SUCCESS = "FETCHING_FRIENDS_SUCCESS";
export const FETCHING_FRIENDS_FAILURE = "FETCHING_FRIENDS_FAILURE";

//Search Friend
export const SEARCHING_FRIENDS = "SEARCHING_FRIENDS";
export const SEARCHING_FRIENDS_SUCCESS = "SEARCHING_FRIENDS_SUCCESS";
export const SEARCHING_FRIENDS_FAILURE = "SEARCHING_FRIENDS_FAILURE";