//Register
export const REGISTERING = "REGISTERING";
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

//Get Rooms
export const FETCHING_ROOMS = "FETCHING_ROOMS";
export const FETCHING_ROOMS_SUCCESS = "FETCHING_ROOMS_SUCCESS";
export const FETCHING_ROOMS_FAILURE = "FETCHING_ROOMS_FAILURE";

//Get Friends List
export const FETCHING_FRIENDS = "FETCHING_FRIENDS";
export const FETCHING_FRIENDS_SUCCESS = "FETCHING_FRIENDS_SUCCESS";
export const FETCHING_FRIENDS_FAILURE = "FETCHING_FRIENDS_FAILURE";

//Search Friend
export const SEARCHING_FRIENDS = "SEARCHING_FRIENDS";
export const SEARCHING_FRIENDS_SUCCESS = "SEARCHING_FRIENDS_SUCCESS";
export const SEARCHING_FRIENDS_FAILURE = "SEARCHING_FRIENDS_FAILURE";

//Get User Info
export const FETCHING_USERINFO = 'FETCHING_USERINFO';
export const FETCHING_USERINFO_SUCCESS = 'FETCHING_USERINFO_SUCCESS';
export const FETCHING_USERINFO_FAILURE = 'FETCHING_USERINFO_FAILURE';

//Get Notifications
export const FETCHING_NOTIFICATIONS = "FETCHING_NOTIFICATIONS";
export const FETCHING_NOTIFICATIONS_SUCCESS = "FETCHING_NOTIFICATIONS_SUCCESS";
export const FETCHING_NOTIFICATIONS_FAILURE = "FETCHING_NOTIFICATIONS_FAILURE";

//GPS
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const START_UPDATE_LOCATION = "START_UPDATE_LOCATION";

//APPOINTMENTS
export const UPDATE_APPOINTMENTS = "UPDATE_APPOINTMENTS";
export const START_UPDATE_APPOINTMENTS = "START_UPDATE_APPOINTMENTS";

//ROUTES
export const UPDATE_ROUTES = "UPDATE_ROUTES";
export const START_UPDATE_ROUTES = "START_UPDATE_ROUTES";

//SOCKET
export const UPDATE_SOCKET = "UPDATE_SOCKET";
export const START_UPDATE_SOCKET = "START_UPDATE_SOCKET";